---
- name: Webhook Ansible EDA
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003

  rules:
    - name: Say Ansible EDA
      condition: event.payload.message == "Ansible EDA"
      action:
        run_job_template:
          name: "Demo Job Template"
          retries: 1
          delay: 10
          set_facts: True
          organization: Default
